[package]
name = "indexer"
description = "An vector space based search engine for local directories"
version = "0.1.0"
edition = "2021"
authors = ["Juan Milkah <juanmilkah@gmail.com>"]
license = "GNU/GPL3"

[dependencies]
poppler = "0.6.0"
rust-stemmers = "1.2.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
stop-words = "0.8.1"
